[package]
name = "pedidosya-courier-rs"
version = "0.1.0"
edition = "2024"
authors = ["alelopezperez"]

[dependencies]
reqwest = { version = "0.12.22", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142" }
