/*
 * PedidosYa Courier API
 *
 * PedidosYa Courier API allows developers to build applications that automates the use of PedidosYa's logistics network. Through this it's possible to ship packages from a pickup point to a dropoff point.  To start using the PedidosYa Courier API you need to Generate an Authentication Token. You could get information about this [here](https://developers.pedidosya.com/courier-doc/first-steps#generate-token). All endpoints require an authorization header with a token value. The content of the header should look like the following: 'Authorization: token' <br> <br>
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfirmedEstimationShippingRequest : This model represents an order that must be confirmed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfirmEstimationShippingRequest {
    /// Delivery Offer ID. If the deliveryOfferId is not specified, the first available offer will be considered valid.
    #[serde(rename = "deliveryOfferId", skip_serializing_if = "Option::is_none")]
    pub delivery_offer_id: Option<String>,
}

impl ConfirmEstimationShippingRequest {
    /// This model represents an order that must be confirmed.
    pub fn new() -> Self {
        Self {
            delivery_offer_id: None,
        }
    }
}
