/*
 * PedidosYa Courier API
 *
 * PedidosYa Courier API allows developers to build applications that automates the use of PedidosYa's logistics network. Through this it's possible to ship packages from a pickup point to a dropoff point.  To start using the PedidosYa Courier API you need to Generate an Authentication Token. You could get information about this [here](https://developers.pedidosya.com/courier-doc/first-steps#generate-token). All endpoints require an authorization header with a token value. The content of the header should look like the following: 'Authorization: token' <br> <br>
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimationShippingResponse : This model represents a shipping estimate order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimationShippingResponse {
    /// Shipping estimate identifier
    #[serde(rename = "estimateId", skip_serializing_if = "Option::is_none")]
    pub estimate_id: Option<String>,
    /// Client Internal Reference ID
    #[serde(rename = "referenceId", skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<String>,
    /// If you are creating a TEST shipping, set this field true
    #[serde(rename = "isTest", skip_serializing_if = "Option::is_none")]
    pub is_test: Option<bool>,
    /// List of items shipped in the package
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::ShippingItemRequest>>,
    /// Geographical points where transport should go. There must be two waypoints, one with type PICK_UP & one DROP_OFF. The geographical points must be inside the PedidosYa fleet's working zone. You can obtain the working zones in the endpoint <a href='#tag/Coverage/paths/~1v3~1working-zones/get'>Get Working Zones</a>.
    #[serde(rename = "waypoints", skip_serializing_if = "Option::is_none")]
    pub waypoints: Option<Vec<models::WayPointModelResponse>>,
    /// Delivery offers available for the estimation. This field has data related to delivery type, price and times info.
    #[serde(rename = "deliveryOffers", skip_serializing_if = "Option::is_none")]
    pub delivery_offers: Option<Vec<models::DeliveryOffer>>,
    #[serde(rename = "route", skip_serializing_if = "Option::is_none")]
    pub route: Option<Box<models::Route>>,
    /// This email will be used to send shipping confirmation and cancellation notifications to the end user.
    #[serde(rename = "notificationMail", skip_serializing_if = "Option::is_none")]
    pub notification_mail: Option<String>,
}

impl EstimationShippingResponse {
    /// This model represents a shipping estimate order.
    pub fn new() -> EstimationShippingResponse {
        EstimationShippingResponse {
            estimate_id: None,
            reference_id: None,
            is_test: None,
            items: None,
            waypoints: None,
            delivery_offers: None,
            route: None,
            notification_mail: None,
        }
    }
}
