/*
 * PedidosYa Courier API
 *
 * PedidosYa Courier API allows developers to build applications that automates the use of PedidosYa's logistics network. Through this it's possible to ship packages from a pickup point to a dropoff point.  To start using the PedidosYa Courier API you need to Generate an Authentication Token. You could get information about this [here](https://developers.pedidosya.com/courier-doc/first-steps#generate-token). All endpoints require an authorization header with a token value. The content of the header should look like the following: 'Authorization: token' <br> <br>
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShippingRoute : Route assigned to the shipping. This field has data related to delivery type, price and times info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShippingRoute {
    /// Delivery mode.   The EXPRESS mode means a shipping order that will be delivered 'as soon as possible'.   The SCHEDULED mode means a shipping order that will be delivered 'in a specific time frame'.
    #[serde(rename = "deliveryMode", skip_serializing_if = "Option::is_none")]
    pub delivery_mode: Option<DeliveryMode>,
    /// Estimated pick-up time in UTC. Format ISO 8601: YYYY-MM-DDTHH:MM:SSZ
    #[serde(
        rename = "estimatedPickUpTime",
        skip_serializing_if = "Option::is_none"
    )]
    pub estimated_pick_up_time: Option<String>,
    /// Estimated delivery time in UTC. Format ISO 8601: YYYY-MM-DDTHH:MM:SSZ
    #[serde(
        rename = "estimatedDeliveryTime",
        skip_serializing_if = "Option::is_none"
    )]
    pub estimated_delivery_time: Option<String>,

    /// Estimated delivery time in UTC. Format ISO 8601: YYYY-MM-DDTHH:MM:SSZ
    #[serde(rename = "deliveryTimeFrom", skip_serializing_if = "Option::is_none")]
    pub delivery_time_from: Option<String>,

    /// Estimated delivery time in UTC. Format ISO 8601: YYYY-MM-DDTHH:MM:SSZ
    #[serde(rename = "deliveryTimeTo", skip_serializing_if = "Option::is_none")]
    pub delivery_time_to: Option<String>,

    /// Shipping total distance in meters
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    #[serde(rename = "pricing", skip_serializing_if = "Option::is_none")]
    pub pricing: Option<Box<models::ShippingRoutePricing>>,
}

impl ShippingRoute {
    /// Route assigned to the shipping. This field has data related to delivery type, price and times info.
    pub fn new() -> ShippingRoute {
        ShippingRoute {
            delivery_mode: None,
            estimated_pick_up_time: None,
            estimated_delivery_time: None,
            distance: None,
            pricing: None,
            delivery_time_from: None,
            delivery_time_to: None,
        }
    }
}
/// Delivery mode.   The EXPRESS mode means a shipping order that will be delivered 'as soon as possible'.   The SCHEDULED mode means a shipping order that will be delivered 'in a specific time frame'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeliveryMode {
    #[serde(rename = "EXPRESS")]
    Express,
    #[serde(rename = "SCHEDULED")]
    Scheduled,
    #[serde(rename = "SCHEDULE")]
    Schedule,
}

impl Default for DeliveryMode {
    fn default() -> DeliveryMode {
        Self::Express
    }
}
