/*
 * PedidosYa Courier API
 *
 * PedidosYa Courier API allows developers to build applications that automates the use of PedidosYa's logistics network. Through this it's possible to ship packages from a pickup point to a dropoff point.  To start using the PedidosYa Courier API you need to Generate an Authentication Token. You could get information about this [here](https://developers.pedidosya.com/courier-doc/first-steps#generate-token). All endpoints require an authorization header with a token value. The content of the header should look like the following: 'Authorization: token' <br> <br>
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ShippingRequestRequirements : Contains shipping requirement fields.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShippingRequestRequirements {
    /// If cash collection is enabled in the partner configuration, this boolean includes the shipping cost in the total to be charged in pick up and drop off. This functionality is not turned on by default.
    #[serde(rename = "includeDeliveryFee", skip_serializing_if = "Option::is_none")]
    pub include_delivery_fee: Option<bool>,
}

impl ShippingRequestRequirements {
    /// Contains shipping requirement fields.
    pub fn new() -> ShippingRequestRequirements {
        ShippingRequestRequirements {
            include_delivery_fee: None,
        }
    }
}
